"""empty message

Revision ID: 70cccb5695b9
Revises: fa374ffdc952
Create Date: 2024-12-22 03:11:14.318020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cccb5695b9'
down_revision: Union[str, None] = 'fa374ffdc952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rooms_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('users_room_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_room_id_fkey', 'users', 'rooms', ['room_id'], ['id'])
    op.drop_table('user_rooms_association')
    # ### end Alembic commands ###
