"""empty message

Revision ID: ad0b1bef6ff9
Revises: 70cccb5695b9
Create Date: 2024-12-22 03:12:19.329740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0b1bef6ff9'
down_revision: Union[str, None] = '70cccb5695b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'password')
    # ### end Alembic commands ###
