"""empty message

Revision ID: b594c9ba48cb
Revises: 6886e9e4d007
Create Date: 2024-12-22 01:40:21.740813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b594c9ba48cb'
down_revision: Union[str, None] = '6886e9e4d007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'room_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'room_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
