"""empty message

Revision ID: fa374ffdc952
Revises: b594c9ba48cb
Create Date: 2024-12-22 03:01:11.779010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa374ffdc952'
down_revision: Union[str, None] = 'b594c9ba48cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('host_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'users', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'host_id')
    # ### end Alembic commands ###
